startupMessage: App is starting up...
terminationMessage: App is stopping now...
everyMessage: every time I think of you...
onMessage: on time again...

server:
  type: simple
  connector:
    type: http
    port: 8090
